# Common variables for all the services
# 'production' only prints info and above. 'development' also prints debug
environment: "production"
aligned_layer_deployment_config_file_path: "./contracts/script/output/devnet/alignedlayer_deployment_output.json"
eigen_layer_deployment_config_file_path: "./contracts/script/output/devnet/eigenlayer_deployment_output.json"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8545"
eigen_metrics_ip_port_address: "localhost:9090"

## ECDSA Configurations
ecdsa:
  private_key_store_path: "config-files/anvil.batcher.ecdsa.key.json"
  private_key_store_password: ""

## Batcher configurations
batcher:
  block_interval: 3
  batch_size_interval: 10
  max_proof_size: 67108864 # 64 MiB
  max_batch_size: 268435456 # 256 MiB
  eth_ws_reconnects: 99999999999999
  pre_verification_is_enabled: true
